spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: user_service_app
    password: user_service_pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true